_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl" #'/home/niudt/robotic_project/detectron2/tools/test_franctal_200/model_final.pth'
  WEIGHTS: '/home/niudt/robotic_project/detectron2/tools/rtx_42subset_gripper_new/model_final.pth'
  MASK_ON: False
  RESNETS:
    DEPTH: 101
#SOLVER:
#  STEPS: (210000, 250000)
#  MAX_ITER: 270000
  ROI_HEADS:
    NUM_CLASSES: 1

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.002
  STEPS: (4600, 5500)
  MAX_ITER: 6000

DATASETS:
  TRAIN: ("rtx_42subset_gripper",)
  TEST: ("push one button",) # TODO: this is need to change based on different subset

OUTPUT_DIR: .